# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Gobierto · Herramientas para conectar con tus vecinos"
description: Gobierto crea herramientas de transparencia y participación que funcionan de verdad para mejorar la comunicación con  tus vecinos 
baseurl: "" # the subpath of your site, e.g. /blog

# default permalink for blog posts
permalink: /blog/:year:month:day-:title.html

collections:
  articles:
    output: true
    permalink: /:year:month:day-:title.html
  static_pages:
    output: true
    permalink: /pages/:path/

# urls for sections/pages
url_producto_presupuestos_visualizacion: "visualizacion_presupuestos_municipales"
url_producto_presupuestos_consultas: 
url_producto_presupuestos_historias: 
url_producto_presupuestos_inteligencia: 

# The configuration entry `url` is generated in plugins/site_url_generator.rb depending on the environment variable
production_url: ""
staging_url: ""
development_url: "http://localhost:4000"

twitter_username: "@gobierto"
twitter_hashtag_for_social_share: '#gobierto'

# Build settings
markdown: kramdown
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', '_config.yml', 'config']

# Reading list data
reading_list_file: reading_list.json

gems: [jekyll-assets]

jekyll-press:
  exclude: '*.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

# Plugin: jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  digest: false
  sources:
    - _assets/javascript
    - _assets/images
    - _assets/stylesheets
  compress:
    js: false
  cachebust: hard
  gzip: [ text/css, application/javascript ]

timezone: America/New_York
